import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

export function emitModelsModule(outPath, entries) {
  mkdirSync(dirname(outPath), { recursive: true });
  const body = Object.entries(entries)
    .map(([id, data]) => {
      const list = (items) => items.map((n) => `      ${JSON.stringify(n)},`).join("\n");
      return `  ${id}: {
    file: ${JSON.stringify(`/models/${id}.glb`)},
    components: [
${list(data.designators)}
    ],
    layers: [
${list(data.layers)}
    ],
    extras: [
${list(data.extras)}
    ],
  },`;
    })
    .join("\n");

  const source = `// GENERATED by scripts/build-models.mjs — do not edit by hand.
// Run \`pnpm models:build\` to regenerate.

export const BOARD_MODELS = {
${body}
} as const;

export type BoardModelId = keyof typeof BOARD_MODELS;
export type BoardModel = (typeof BOARD_MODELS)[BoardModelId];
`;
  writeFileSync(outPath, source, "utf8");
}
