export const SOURCE_DIR = "D:/Project/PCBModel";

export const BOARD_SPECS = {
  keel: {
    source: "Keel.glb",
    designators: 41,
    layers: [
      "Keel_PCB",
      "Keel_PCB_Pads",
      "Keel_PCB_Tracks",
      "Keel_PCB_Zones",
      "Keel_PCB_Silkscreen_Top",
      "Keel_PCB_Silkscreen_Bottom",
      "Keel_PCB_Soldermask_Top",
      "Keel_PCB_Soldermask_Bottom",
    ],
    extras: ["Duct"],
  },
  interim: {
    source: "Interim.glb",
    designators: 54,
    layers: [
      "Interim_PCB",
      "Interim_Pads",
      "Interim_Silk_Front",
      "Interim_Silk_Back",
      "Interim_Mask_Front",
      "Interim_Mask_Back",
    ],
    extras: [],
  },
  fides: {
    source: "Fides.glb",
    designators: 16,
    layers: [
      "Fides_PCB_body",
      "Fides_pads",
      "Fides_copper_zones",
      "Fides_copper_tracks",
      "Fides_silkscreen_top",
      "Fides_silkscreen_bottom",
      "Fides_soldermask_top",
      "Fides_soldermask_bottom",
    ],
    extras: [],
  },
  deltat32: {
    sourcePath: "node_modules/.cache/deltat32/deltat32.source.glb",
    designators: 78,
    layers: [
      "c3_pcb",
      "c3_copper",
      "c3_pads",
      "c3_vias",
      "c3_silkscreen_top",
      "c3_silkscreen_bottom",
      "c3_soldermask_top",
      "c3_soldermask_bottom",
      "bmi_pcb",
      "bmi_copper",
      "bmi_pads",
      "bmi_vias",
      "bmi_silkscreen_top",
      "bmi_silkscreen_bottom",
      "bmi_soldermask_top",
      "bmi_soldermask_bottom",
    ],
    extras: [],
  },
};
